# Generated by Django 4.1.1 on 2022-09-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
