# Generated by Django 4.1.1 on 2022-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogapp', '0002_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='formArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('fecha', models.DateField()),
                ('creador', models.CharField(max_length=140)),
                ('contenido', models.CharField(max_length=128)),
            ],
        ),
    ]
