# Generated by Django 4.1.1 on 2022-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formarticulo',
            name='imagen',
            field=models.FileField(default='1', upload_to=''),
        ),
    ]
