# Generated by Django 4.1.1 on 2022-09-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_formarticulo_imagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formarticulo",
            name="imagen",
        ),
    ]
