# Generated by Django 4.1.1 on 2022-09-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_remove_formarticulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='formarticulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
