# Generated by Django 4.1.1 on 2022-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_formarticulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formarticulo',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='formarticulo',
            name='contenido',
            field=models.CharField(max_length=600),
        ),
    ]
