# Generated by Django 4.1.1 on 2022-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_formarticulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formarticulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenart'),
        ),
    ]
