# Generated by Django 4.1.1 on 2022-09-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilapp', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
