# Generated by Django 4.1.1 on 2022-09-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilapp', '0003_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='usuario',
        ),
    ]
