# Generated by Django 4.1.1 on 2022-09-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilapp', '0005_perfil_imagen_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
    ]
