# Generated by Django 4.1.1 on 2022-09-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilapp', '0006_remove_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
    ]
