# Generated by Django 4.1.1 on 2022-09-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfilapp', '0007_perfil_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='imagen',
        ),
    ]
